[tool.isort]
profile = "black"
split_on_trailing_comma = true
skip_glob = ["*_pb2.py"]

[tool.black]
preview = true
line_length = 79
extend-exclude = '''
    .*_pb2\.py
    | .*\.ipynb
'''

[tool.pylint.MASTER]
extension-pkg-allow-list = "PySide6"
disable = "fixme"
ignore-patterns = [".*_pb2\\.py", "whitelist\\.py"]
# oscillo.py is used by *.ipynb files. The Jupyter versions (*.ipynb) are
# obsolete and will no longer be maintained.
ignore-paths = "oscillodsp/oscillo.py"

[tool.pylint."MESSAGES CONTROL"]
disable = "missing-function-docstring,duplicate-code"
