/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "oscillodsp.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EchoRequest, EchoRequest, AUTO)


PB_BIND(GetWaveGroup, GetWaveGroup, AUTO)


PB_BIND(Terminate, Terminate, AUTO)


PB_BIND(Configure, Configure, AUTO)


PB_BIND(MessageToDSP, MessageToDSP, AUTO)


PB_BIND(Acknowledge, Acknowledge, AUTO)


PB_BIND(EchoReply, EchoReply, AUTO)


PB_BIND(ChannelConfig, ChannelConfig, AUTO)


PB_BIND(ConfigReply, ConfigReply, AUTO)


PB_BIND(Wave, Wave, 2)


PB_BIND(WaveGroup, WaveGroup, 2)


PB_BIND(MessageToHost, MessageToHost, 2)









